### ISSUE TITLE
networktest.twilio.com

### ISSUE THREAD

**Issue by mikev** [twilio/rtc-diagnostics#52]
The UI for rtc-diagnostics is complementary and necessary to actually run the diagnostics.  Are there plans to open source the javascipt  code for the web site at networktest.twilio.com, which is needed to host and run these diagnostics?

**Comment by charliesantos** [comment]
Hey @mikev , thanks for reaching out! Just to give you a little bit of background, networktest.twilio.com has been refactored such that the tests are separate from the UI components. We don't plan on open sourcing networktest.twilio.com. We do however, have the new UI components open sourced. Here are all the links you'd need:

- [RTC Diagnostics SDK](https://github.com/twilio/rtc-diagnostics) - This repository. It contains WebRTC related tests such as audio and video device tests and bitrate tests.
- [VoiceJS Preflight Test](https://github.com/twilio/twilio-client.js/tree/preflight) - Currently in a feature branch. For testing Voice calls
- [Voice Diagnostics Tool](https://github.com/twilio/rtc-diagnostics-react-app) - UI components that demonstrates the use of RTC Diagnostics SDK and VoiceJS Preflight Test.

Please keep in mind that these are still in beta and we are currently adding more UI components and features!
