### ISSUE TITLE
Wrong package tags

### ISSUE THREAD

**Issue by ksocha** [twilio/rtc-diagnostics#56]
**Describe the bug**
Currently, `1.0.0-preview3` has the latest tag. This is clearly wrong, as `1.0.0-beta2` should be tagged as such.

**To Reproduce**
N/A

**Expected behavior**
After installing the package using `npm install @twilio/rtc-diagnostics` or `yarn add @twilio/rtc-diagnostics` I get the latest version of the code.

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by charliesantos** [comment]
Thanks for reporting @ksocha . This issue has been fixed.
