### ISSUE TITLE
Request: Avoid exact versions in package dependencies

### ISSUE THREAD

**Issue by ksocha** [twilio/rtc-diagnostics#57]
**What is the feature that you would like to see in the SDK? Please describe.**
Would it be possible to avoid using exact version matchers in the dependencies of this package? This may cause bundling in multiple versions of the same package into a final users app packages.

**Is your feature request related to a problem? Please describe.**
Rationale explained above.

**Describe alternatives you've considered**
```
  dependencies: {
    '@types/events': '3.0.0',
    '@types/node': '12.12.11',
    events: '3.0.0'
  },
```
could be replaced by: 
```
  dependencies: {
    '@types/events': '^3.0.0',
    '@types/node': '^12.12.11',
    events: '^3.0.0'
  },
```
to avoid bundling in multiple versions of the same package.

**Additional context**
N/A

**Comment by charliesantos** [comment]
Hi @ksocha ,

We prefer to use exact versions to control when our packages get updated, which reduces the risk of potential breaking changes from our dependencies.

Thank you,
Charlie
