### ISSUE TITLE
Can't connect to tcp server "turn:global.turn.twilio.com:3478?transport=tcp" in javascript

### ISSUE THREAD

**Issue by Atominac** [twilio/rtc-diagnostics#58]
In javascript, when trying to make a connection test fails and zero bitrate is received. This started happening after I updated to the new SDK. 

const bitrateTest = testMediaConnectionBitrate({
		iceServers: [{
			credential: "creds",
			username: "username",
			urls: "turn:global.turn.twilio.com:3478?transport=tcp",
		}],
	});

**Comment by charliesantos** [comment]
Hi @Atominac ,

Thanks for submitting!
Looking at your snippet, you would need a STUN server. Please see [MediaConnectionBitrateTest.Options.iceServers](https://twilio.github.io/rtc-diagnostics/interfaces/mediaconnectionbitratetest.options.html#iceservers)  and [changelog](https://github.com/twilio/rtc-diagnostics/blob/master/CHANGELOG.md#changes) for details.

Thanks,
Charlie

**Comment by Atominac** [comment]
Hello, @charliesantos,
Thanks for replying to the issue.
This worked for me.

         {
		credential: "credential",
		username: "username",
		urls: ["turn:global.turn.twilio.com:3478?transport=tcp","stun:global.stun.twilio.com:3478?transport=tcp"],
	}

Thanx for you help
