### ISSUE TITLE
Is it possible to pass an audio file generated in the audio input test to the audio output test?

### ISSUE THREAD

**Issue by mdekhtiarenko** [twilio/rtc-diagnostics#64]
Hi,
I would like to pass an audio file that was generated from the audio input test to the audio output test. So user will hear himself. When I use any file by the regular url it works just fine. But when I pass that recordingUrl that was returned it's silent. Probably because it's a blob file.
Could please advice here? Is there any way to play it in the audio output test?

**Comment by charliesantos** [comment]
Hi @mdekhtiarenko, thanks for reaching out!
We have an example react app that does exactly this. See our repo [here](https://github.com/twilio/rtc-diagnostics-react-app).

**Comment by mdekhtiarenko** [comment]
Wow, that was really fast!
Thanks for you response @charliesantos. I will check it out.

**Comment by charliesantos** [comment]
Awesome! I'll close this issue now. Please let us know if you have further questions.
