### ISSUE TITLE
Generation of credentials for MediaConnectionBitrateTest using Java

### ISSUE THREAD

**Issue by mdekhtiarenko** [twilio/rtc-diagnostics#65]
Hi there,
In your example [here](https://twilio.github.io/rtc-diagnostics/interfaces/mediaconnectionbitratetest.options.html#iceservers) you are using [this twilio node module](https://www.npmjs.com/package/twilio) to generate token and then grab iceServer urls. Also you don't recommend to do this in the browser. 
However our servers are build on Java I can't find how to do it using [your library for Java](https://mvnrepository.com/artifact/com.twilio.sdk/twilio). Could you please point me to the documentation how to do it? Or should I use another one?

**Comment by charliesantos** [comment]
Hey @mdekhtiarenko , you will need the twili java helper library. Please see this page for installation instructions https://www.twilio.com/docs/libraries/java#install-the-sdk-locally

And check this page for examples on how to generate the token. Click the JAVA tab https://www.twilio.com/docs/stun-turn/api

**Comment by mdekhtiarenko** [comment]
Thanks a lot! I was searching for it in packages related to video...
