### ISSUE TITLE
Speaker check for FireFox is unaware that all speakers are disabled

### ISSUE THREAD

**Issue by hamiltonken** [twilio/rtc-diagnostics#66]
**Describe the bug**
On Microsoft Windows, all speakers can be disabled at the system level.  Nevertheless, when the speaker check is run within Firefox, we detect that the speaker test is emitting volume events as if thee were a speaker available. 

**To Reproduce**
We have a progress bar that proceeds on the reception of non-zero volume events.  Alternatively one could enable a listener and record the reception of volume events in the browser console.  So to begin, go to Windows control for sound devices and disable all, including the headphone jack. Execute the speaker test within Firefox and note that volume events are emitted as if the tones were actually being generated.

**Expected behavior**
We would expect that there would be some recognition, either an exception thrown or just a lack of non-zero volume events emitted.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser: [e.g. Chrome 80, Firefox 72]
 - App Version: [e.g. 0.1.0]
 - SDK Version: [e.g 2.1.0]
 - Node.js version: [e.g. 12.14.1]

**Additional context**

**Comment by mhuynh5757** [comment]
Hi @hamiltonken, thanks for bringing this up to our attention. This is unfortunately a browser limitation within Firefox and unaddressable by us at this time. Firefox is currently missing support for proper output device enumeration and output device selection.

**Comment by mhuynh5757** [comment]
I'll close this now since it's not actionable but feel free to follow up.
