### ISSUE TITLE
'No Audio Detected' on video-diagnostics.twilio.com app using newest version of MacOs(Ventura), IpadOs (16) 

### ISSUE THREAD

**Issue by maximv21** [twilio/rtc-diagnostics#81]
We are using video-diagnostics.twilio.com to test audio/video quality.
On the "Test your audio test" after pressing "Record" then 'Play back' button we see the error 'No Audio Detected' and we can't hear any sound.
This happens only on new versions of MacOs(Ventura), IpadOs (16).

Previous versions were working well 

Steps to reproduce the behavior.
- Go to diagnostic app https://video-diagnostics.twilio.com/
- Go through the steps till "Test your audio test"
- Press "Record" button 
- Press 'Play back' button
- Error  'No Audio Detected' should appear without any sound.

Environment:
 - OS: MacOs(Ventura), IpadOs (16) 
 - Browser: [Chrome, Safari]

**Comment by charliesantos** [comment]
Hi @maximv21 this should be fixed by this https://github.com/twilio/rtc-diagnostics/pull/70 which will go out soon.
